project:
  type: book

book:
  title: "Remotely sensing learning diary"
  author: "Yuhao CHEN"
  date: "17/01/2024"
  chapters:
  - index.qmd
  - week_1.qmd 
  - week_2.qmd
  - week_3.qmd
  - references.qmd

bibliography: references.bib

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo

editor: visual

