project:
  type: website
  output-dir: docs

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - intro.qmd
      - week_1.qmd 

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

