project:
  type: book

book:
  title: "Remotely sensing learning diary"
  author: "Yuhao CHEN"
  date: "17/01/2024"
  chapters:
  - index.qmd
  - intro.qmd
  - week_1.qmd 
  - week_2.qmd

bibliography: references.bib

output-dir: "docs"

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo

editor: visual

